-- ROOT 아이템을 찾아 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME)을 출력하는 SQL문을 작성
-- 아이템 ID를 기준으로 오름차순 정렬
-- PARENT 아이템이 없는 아이템을 ROOT 아이템
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME
FROM ITEM_INFO, ITEM_TREE
WHERE ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
AND PARENT_ITEM_ID IS NULL;